Code coverage
sonr-io/ts-modules pull request #23
Opened 2022-05-13 18:09 UTC by brokecollegekidwithaclothingobsession

Added Code Coverage to the Master branch

## Changes

- Build and Test refactored for Code Coverage
- Additional Jest Configurations for Coverage
- Added coverage/ and shell file to .gitignore
- Updated test command to run coverage 
- Combined Buffer2String and String2Buffer

## API Updates

### New Features *(required)*

Added CodeCov to the library

### Deprecations *(required)*

N/A

### Enhancements *(optional)*

Code Coverage Testing

## Checklist

- [x] Unit tests
- [x] Documentation

## References *(optional)*

Fixes 
Connects

2022-05-17 20:13 UTC, ntindle requested changes

2022-05-17 20:13 UTC, ntindle commented on jest.config.js
> +            "packages/sonr-webauthn/*/**.{js,jsx,ts,tsx}"
Collect across all packages

2022-05-24 18:35 UTC, brokecollegekidwithaclothingobsession commented on jest.config.js
> +            "packages/sonr-webauthn/*/**.{js,jsx,ts,tsx}"
Fixed, sorry for the late reply.

2022-05-27 16:54 UTC, ntindle approved these changes

2022-06-03 14:06 UTC, merged